---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-rollout-
spec:
  serviceAccountName: tekton
  params:
    - name: SOURCE_URL
      value: ''
    - name: IMAGE
      value: ''
    - name: IMAGE_REGISTRY
      value: ''
    - name: IMAGE_REPOSITORY
      value: ''
    - name: DOCKERFILE
      value: ''
  pipelineRef:
    name: build-and-rollout
  workspaces:
    - name: ssh-creds
      secret:
        secretName: ssh-auth
    - name: build
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 2Gi
    - name: registry-credentials
      secret:
        secretName: docker-hub
        items:
          - key: .dockerconfigjson
            path: auth
