---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: REGISTRY
      description: Which Container registry to utilize
      default: quay.io
    - name: IMAGE
      description: "Reference of the image buildah will produce. Should include repository in its name: repository/image"
    - name: IMAGE_TAG
      description: Tag for the newly built image
      default: latest
    - name: STORAGE_DRIVER
      description: Set buildah storage driver
      default: overlay
    - name: DOCKERFILE_PATH 
      description: "Path to the Dockerfile to build. Give full path to the Dockerfile in repository: path/to/Dockerfile"
      default: Dockerfile
  workspaces:
    - name: builder
  steps:
    - name: build
      image: quay.io/containers/buildah@sha256:514320ef97825ee226a0d7ad9ebc348ca508234e0a8a7b393b48451b77ec17ba
      workingDir: $(workspaces.builder.path)
      securityContext:
        privileged: true
      script: |
        buildah --storage-driver=$(params.STORAGE_DRIVER) build --no-cache -f $(params.DOCKERFILE_PATH) -t $(params.REGISTRY)/$(params.IMAGE):$(params.IMAGE_TAG) .
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
    - name: push
      image: quay.io/containers/buildah@sha256:514320ef97825ee226a0d7ad9ebc348ca508234e0a8a7b393b48451b77ec17ba
      workingDir: $(workspaces.builder.path)
      securityContext:
        privileged: true
      script: |
        buildah --storage-driver=$(params.STORAGE_DRIVER) push --authfile /tmp/authfile/auth $(params.REGISTRY)/$(params.image):$(params.IMAGE_TAG)
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
        - name: image-secret
          mountPath: /tmp/authfile
  volumes:
    - name: varlibcontainers
      emptyDir: {}
    - name: image-secret
      secret:
        secretName: image-pull-secret
        items:
          - key: .dockerconfigjson
            path: auth
